
package com.sistemas.facturacion.service.afipService.wsaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginCMSService", targetNamespace = "https://wsaa.afip.gov.ar/ws/services/LoginCms", wsdlLocation = "file:/home/fcostantino/Workspace/PROYECTO/facturacion/wsdl/wsaa.wsdl")
public class LoginCMSService
    extends Service
{

    private final static URL LOGINCMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINCMSSERVICE_EXCEPTION;
    private final static QName LOGINCMSSERVICE_QNAME = new QName("https://wsaa.afip.gov.ar/ws/services/LoginCms", "LoginCMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/fcostantino/Workspace/PROYECTO/facturacion/wsdl/wsaa.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINCMSSERVICE_WSDL_LOCATION = url;
        LOGINCMSSERVICE_EXCEPTION = e;
    }

    public LoginCMSService() {
        super(__getWsdlLocation(), LOGINCMSSERVICE_QNAME);
    }

    public LoginCMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINCMSSERVICE_QNAME, features);
    }

    public LoginCMSService(URL wsdlLocation) {
        super(wsdlLocation, LOGINCMSSERVICE_QNAME);
    }

    public LoginCMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINCMSSERVICE_QNAME, features);
    }

    public LoginCMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginCMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginCMS
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMS getLoginCms() {
        return super.getPort(new QName("https://wsaa.afip.gov.ar/ws/services/LoginCms", "LoginCms"), LoginCMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginCMS
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMS getLoginCms(WebServiceFeature... features) {
        return super.getPort(new QName("https://wsaa.afip.gov.ar/ws/services/LoginCms", "LoginCms"), LoginCMS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINCMSSERVICE_EXCEPTION!= null) {
            throw LOGINCMSSERVICE_EXCEPTION;
        }
        return LOGINCMSSERVICE_WSDL_LOCATION;
    }

}
