
package com.sistemas.facturacion.service.afipService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginCMS", targetNamespace = "https://wsaa.afip.gov.ar/ws/services/LoginCms")
@XmlSeeAlso({
    com.sistemas.facturacion.service.afipService.wsaa.desein.ObjectFactory.class,
    com.sistemas.facturacion.service.afipService.wsaa.ObjectFactory.class
})
public interface LoginCMS {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     * @throws LoginFault_Exception
     */
    @WebMethod
    @WebResult(name = "loginCmsReturn", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
    @RequestWrapper(localName = "loginCms", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCms")
    @ResponseWrapper(localName = "loginCmsResponse", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCmsResponse")
    public String loginCms(
            @WebParam(name = "in0", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
                    String in0)
        throws LoginFault_Exception
    ;

}
